version: '3.1'
services:
  web:
    image: nginx
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./site.key:/run/secrets/site.key
     - ./site.crt:/run/secrets/site.crt
    ports:
     - "443:443"
     - "80:80"
    command: nginx -g 'daemon off;'
  node:
    build:
      context: .
